### ISSUE TITLE
API 요청 건의

### ISSUE THREAD

**Issue by 97baek** [LM-channel-team-project/kiwee.dev#25]
## 요구사항

- [x] 북마크 POST 요청
- [x] 방문한 게시글 PATCH 요청
- [x] 방문한 게시물 카운트 조회
- [x] 좋아요 누른 게시물 카운트 조회
- [x] 좋아요 누른 게시물 목록 조회
- [x] 방문한 게시물 목록 조회

**Comment by Jungho-Cheon** [comment]
article의 좋아요 갯수는 응답 객체에서 likes 배열의 length를 사용하면 될 것 같습니다.
